services:
  backend:
    build:
      context: ./Server
    image: marubouzo/social-media-backend:latest
    container_name: social_backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB=mongodb://mongo:27017/mydb
      - PORT=8080
      - JWT_KEY=supersecureandlongsecretkey1234567890
    depends_on:
      - mongo
    networks:
      - social-net

  frontend:
    build:
      context: ./client
    image: marubouzo/clinic_booking:latest
    container_name: social_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - social-net

  mongo:
    image: mongo:6.0
    container_name: social_mongo
    ports:
      - "27017:27017"
    volumes:
      - social_mongo_data:/data/db
    networks:
      - social-net

  mongo-express:
    image: mongo-express:latest
    container_name: social_mongo_express
    restart: always
    ports:
      - "8082:8081"  # GUI MongoDB
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - social-net

volumes:
  social_mongo_data:

networks:
  social-net:
    driver: bridge
